
FROM debian:buster-slim
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update && apt-get -y install python3 python3-pip curl nano procps
RUN pip3 install --upgrade pip && pip3 install flask && pip3 install pytz
WORKDIR /app
COPY app_test.py app.py
CMD ["python3", "app.py"]


# This dockerfile is instructions to create the docker image. It is used to build the image. The image starts/runs the container.

# The app_test.py code is the code that is run in line 7. It creates a flask server. A flask server is a type of application server (see definition below). It hosts the back-end logic of our web app.

# APPLICAION SERVER definition:  An application server hosts application back ends that user clients (front ends, web apps, or locally installed applications ) in the network connect to and use. These servers do not need to be a part of the World Wide Web; any local network would do.


#COPY app_test.py /app
#CMD ["python3', "app_test.py"]
